name = "Spectralarity"
author = "EsetKalenko"
version = "v7d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0da4c0ee0654eee94c05990a973b3f34e893c856960fa5670446a89db23df7ef"

[versions]
minecraft = "1.19.2"
quilt = "0.25.0"
