name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89699bed0dc98a996d0ab5c96689f5c8d3287008a4306661bd53ccb41799903a"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
