name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77519c04dbf4b58e8b2ac2cf914b580c5aff343d9d29a4edfb12b864b9b25bc4"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
