name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "678f5475db11edba05ae57e0ec7ce9eccdfed75287f83a404d91da75101bd91d"

[versions]
minecraft = "1.19.2"
quilt = "0.25.0"
