name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12d4e16bca5c5327fc0e4b6372032b09e29efbbb05f1479b8bd4497a470a0459"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
