name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87084ceefbe930d7aac83afd08b9a68775b53bdfa7956c3ffc60fd0625238327"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
