name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca307fb553dad9b4411486002246f714b985f9cfc8ec07bcbb04ae70447b8c8b"

[versions]
minecraft = "1.19.2"
quilt = "0.29.0"
