name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fff67448eadd14fa5367a7ac83e2b1b9a0eb590e911ebcaf3119b57e9cdc01f"

[versions]
minecraft = "1.19.2"
quilt = "0.29.0"
