name = "Spectralarity"
author = "EsetKalenko"
version = "v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bbe68b97c61f98cc41434b9a419bbc60ffc10a86fe7c6b2ec8db914dabc6d72"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
