
# Contains the main zoom features.
[features]
	# Defines the cinematic camera while zooming.
	# "OFF" disables the cinematic camera.
	# "VANILLA" uses Vanilla's cinematic camera.
	# "MULTIPLIED" is a multiplied variant of "VANILLA".
	# options: OFF, VANILLA, MULTIPLIED
	# default: Optional[OFF]
	cinematic_camera = "OFF"
	# Reduces the mouse sensitivity when zooming.
	# default: Optional[true]
	reduce_sensitivity = true
	# Adds transitions between zooms.
	# "OFF" disables transitions.
	# "SMOOTH" replicates Vanilla's dynamic FOV.
	# "LINEAR" removes the smoothiness.
	# options: OFF, SMOOTH, LINEAR
	# default: Optional[SMOOTH]
	zoom_transition = "SMOOTH"
	# The behavior of the zoom key.
	# "HOLD" needs the zoom key to be hold.
	# "TOGGLE" has the zoom key toggle the zoom.
	# "PERSISTENT" makes the zoom permanent.
	# options: HOLD, TOGGLE, PERSISTENT
	# default: Optional[HOLD]
	zoom_mode = "TOGGLE"
	# Allows to increase or decrease zoom by scrolling.
	# default: Optional[true]
	zoom_scrolling = true
	# Adds zoom manipulation keys along with the zoom key.
	# default: Optional[true]
	extra_key_binds = true
	# Adds an overlay in the screen during zoom.
	# "VIGNETTE" uses a vignette as the overlay.
	# "SPYGLASS" uses the spyglass overlay with the vignette texture.
	# The vignette texture can be found at: assets/ok_zoomer/textures/misc/zoom_overlay.png
	# options: OFF, VIGNETTE, SPYGLASS
	# default: Optional[OFF]
	zoom_overlay = "OFF"
	# Determines how the zoom will depend on the spyglass.
	# "REQUIRE_ITEM" will make zooming require a spyglass.
	# "REPLACE_ZOOM" will replace spyglass's zoom with Ok Zoomer's zoom.
	# "BOTH" will apply both options at the same time.
	# The "REQUIRE_ITEM" option is configurable through the ok_zoomer:zoom_dependencies item tag.
	# options: OFF, REQUIRE_ITEM, REPLACE_ZOOM, BOTH
	# default: Optional[OFF]
	spyglass_dependency = "OFF"

# Contains precise configuration of the zoom.
[values]
	# The divisor applied to the FOV when zooming.
	# range[2.2250738585072014E-308, 1.7976931348623157E308]
	# default: Optional[4.0]
	zoom_divisor = 4.0
	# The minimum value that you can scroll down.
	# range[2.2250738585072014E-308, 1.7976931348623157E308]
	# default: Optional[1.0]
	minimum_zoom_divisor = 1.0
	# The maximum value that you can scroll down.
	# range[2.2250738585072014E-308, 1.7976931348623157E308]
	# default: Optional[50.0]
	maximum_zoom_divisor = 50.0
	# The number of steps between the zoom divisor and the maximum zoom divisor.
	# Used by zoom scrolling.
	# range[0, 2147483647]
	# default: Optional[10]
	upper_scroll_steps = 10
	# The number of steps between the zoom divisor and the minimum zoom divisor.
	# Used by zoom scrolling.
	# range[0, 2147483647]
	# default: Optional[5]
	lower_scroll_steps = 5
	# The multiplier used for smooth transitions.
	# range[2.2250738585072014E-308, 1.0]
	# default: Optional[0.75]
	smooth_multiplier = 0.75
	# The multiplier used for the multiplied cinematic camera.
	# range[2.2250738585072014E-308, 4.0]
	# default: Optional[4.0]
	cinematic_multiplier = 4.0
	# The minimum value which the linear transition step can reach.
	# range[0.0, 1.7976931348623157E308]
	# default: Optional[0.125]
	minimum_linear_step = 0.125
	# The maximum value which the linear transition step can reach.
	# range[0.0, 1.7976931348623157E308]
	# default: Optional[0.25]
	maximum_linear_step = 0.25

# Contains options that are unlikely to be changed from the defaults.
[tweaks]
	# Allows for resetting the zoom with the middle mouse button.
	# default: Optional[true]
	reset_zoom_with_mouse = true
	# If enabled, the current zoom divisor is forgotten once zooming is done.
	# default: Optional[true]
	forget_zoom_divisor = true
	# If pressed, the "Save Toolbar Activator" keybind will be unbound if there's a conflict with the zoom key.
	# default: Optional[true]
	unbind_conflicting_key = false
	# If enabled, the spyglass overlay texture is used instead of Ok Zoomer's overlay texture.
	# default: Optional[false]
	use_spyglass_texture = false
	# If enabled, the zoom will use spyglass sounds on zooming in and out.
	# default: Optional[false]
	use_spyglass_sounds = false
	# Shows toasts when the server imposes a restriction.
	# default: Optional[true]
	show_restriction_toasts = true
	# Prints a random owo in the console when the game starts. Enabled by default until full release.
	# default: Optional[true]
	print_owo_on_start = true

